[jim]
token = "" # put your discord token here
default_prefix = "-dev" # all guilds will use this prefix unless changed
shard_count = 1 # amount of shards jim will create

[database]
user = "postgres"
pass = "postgres"
host = "localhost"
name = "dev"
port = 5432

[metrics] # keys can be gathered from datadog
enabled = false
api_key = ""
app_key = ""
host = "jim_dev"
flush_interval = 3 # seconds

[botlist]
enabled = false # be careful with enabling this, bot will fail every time it tries to update lists if you have missing tokens

# $id is the placeholder for bot's user id
[[botlist.list]]
name = "Discord Bots (pw)"
url = "https://bots.discord.pw/api/bots/$id/stats"
token = ""
ignore_errors = true # their server keeps shitting itself, shame 🔔


[[botlist.list]]
name = "Discord Bot List"
url = "https://discordbots.org/api/bots/$id/stats"
token = ""
ignore_errors = false

[oauth]
client_id = "" # your client_id given by discord
client_secret = "" # your client_secret given by discord
redirect_uri = "" # uri you set in developer panel

[server]
secret = "" # secret to be used with JWT
base_url = "http://safetyjim.xyz"
port = 8080